name: sethStore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.8
  connectivity_plus: ^3.0.3
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.6
  firebase_messaging: ^14.1.1
  flutter_rating_bar: ^4.0.0
  flutter_html: ^3.0.0-alpha.2
  photo_view: ^0.14.0
  firebase_auth: ^4.7.3
  sms_autofill: ^2.2.0
  intl: ^0.17.0
  country_code_picker: ^2.0.2
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  file_picker: ^5.2.2
  shimmer: ^2.0.0
  geocoding: ^2.0.5
  razorpay_flutter: ^1.2.7
  #flutter_paystack: ^1.0.6
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  #flutter_paystack: ^1.0.5+1
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^10.1.0
  in_app_review: ^2.0.3
  firebase_dynamic_links: ^5.0.6
  open_filex: ^4.3.1
  provider: ^6.0.1
  video_player: ^2.2.7
  flutter_svg: ^2.0.1
  paytm: ^3.0.1
  youtube_player_flutter: ^8.1.0
  share_plus: ^6.3.0
  package_info_plus: ^3.0.3
  url_launcher: ^6.0.12
  version: ^3.0.2
  flutter_downloader: ^1.9.1
  speech_to_text: ^6.0.0
  tuple: ^2.0.0
  image_picker: ^0.8.4+4
  bottom_bar: ^2.0.0
  sqflite: ^2.0.1
  webview_flutter: ^4.0.4
  flutter_stripe: ^8.0.0+1
  lottie: ^2.0.0
  flutter_styled_toast: ^2.1.3
  firebase_core: ^2.14.0
  my_fatoorah: ^3.1.0
  google_sign_in: ^6.1.0
  flutter_widget_from_html: ^0.10.1
  sign_in_with_apple: ^5.0.0
  intl_phone_field: ^3.1.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/eShop.db
    - assets/animation/maintenance.json
    - lib/Language/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf